// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: pvz_service.proto

package grpc_profile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PVZReportService_GetPVZReport_FullMethodName = "/pvz_service.PVZReportService/GetPVZReport"
)

// PVZReportServiceClient is the client API for PVZReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PVZReportServiceClient interface {
	GetPVZReport(ctx context.Context, in *PVZReportRequest, opts ...grpc.CallOption) (*PVZReportResponse, error)
}

type pVZReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPVZReportServiceClient(cc grpc.ClientConnInterface) PVZReportServiceClient {
	return &pVZReportServiceClient{cc}
}

func (c *pVZReportServiceClient) GetPVZReport(ctx context.Context, in *PVZReportRequest, opts ...grpc.CallOption) (*PVZReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PVZReportResponse)
	err := c.cc.Invoke(ctx, PVZReportService_GetPVZReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PVZReportServiceServer is the server API for PVZReportService service.
// All implementations must embed UnimplementedPVZReportServiceServer
// for forward compatibility.
type PVZReportServiceServer interface {
	GetPVZReport(context.Context, *PVZReportRequest) (*PVZReportResponse, error)
	mustEmbedUnimplementedPVZReportServiceServer()
}

// UnimplementedPVZReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPVZReportServiceServer struct{}

func (UnimplementedPVZReportServiceServer) GetPVZReport(context.Context, *PVZReportRequest) (*PVZReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPVZReport not implemented")
}
func (UnimplementedPVZReportServiceServer) mustEmbedUnimplementedPVZReportServiceServer() {}
func (UnimplementedPVZReportServiceServer) testEmbeddedByValue()                          {}

// UnsafePVZReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PVZReportServiceServer will
// result in compilation errors.
type UnsafePVZReportServiceServer interface {
	mustEmbedUnimplementedPVZReportServiceServer()
}

func RegisterPVZReportServiceServer(s grpc.ServiceRegistrar, srv PVZReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedPVZReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PVZReportService_ServiceDesc, srv)
}

func _PVZReportService_GetPVZReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PVZReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PVZReportServiceServer).GetPVZReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PVZReportService_GetPVZReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PVZReportServiceServer).GetPVZReport(ctx, req.(*PVZReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PVZReportService_ServiceDesc is the grpc.ServiceDesc for PVZReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PVZReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pvz_service.PVZReportService",
	HandlerType: (*PVZReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPVZReport",
			Handler:    _PVZReportService_GetPVZReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pvz_service.proto",
}
