// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pvz_service.proto

package grpc_profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PVZReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVZReportRequest) Reset() {
	*x = PVZReportRequest{}
	mi := &file_pvz_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZReportRequest) ProtoMessage() {}

func (x *PVZReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZReportRequest.ProtoReflect.Descriptor instead.
func (*PVZReportRequest) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{0}
}

func (x *PVZReportRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PVZReportRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PVZReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *PVZReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type PVZReportResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Error         string                  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Reports       *PVZReportAggregateList `protobuf:"bytes,2,opt,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVZReportResponse) Reset() {
	*x = PVZReportResponse{}
	mi := &file_pvz_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZReportResponse) ProtoMessage() {}

func (x *PVZReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZReportResponse.ProtoReflect.Descriptor instead.
func (*PVZReportResponse) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{1}
}

func (x *PVZReportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PVZReportResponse) GetReports() *PVZReportAggregateList {
	if x != nil {
		return x.Reports
	}
	return nil
}

type PVZReportAggregateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*PVZReportAggregate  `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVZReportAggregateList) Reset() {
	*x = PVZReportAggregateList{}
	mi := &file_pvz_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZReportAggregateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZReportAggregateList) ProtoMessage() {}

func (x *PVZReportAggregateList) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZReportAggregateList.ProtoReflect.Descriptor instead.
func (*PVZReportAggregateList) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{2}
}

func (x *PVZReportAggregateList) GetValues() []*PVZReportAggregate {
	if x != nil {
		return x.Values
	}
	return nil
}

type ReceptionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Reception           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceptionList) Reset() {
	*x = ReceptionList{}
	mi := &file_pvz_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceptionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceptionList) ProtoMessage() {}

func (x *ReceptionList) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceptionList.ProtoReflect.Descriptor instead.
func (*ReceptionList) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReceptionList) GetValues() []*Reception {
	if x != nil {
		return x.Values
	}
	return nil
}

type PVZReportAggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvz           *PVZ                   `protobuf:"bytes,1,opt,name=pvz,proto3" json:"pvz,omitempty"`
	Receptions    *ReceptionList         `protobuf:"bytes,2,opt,name=receptions,proto3" json:"receptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVZReportAggregate) Reset() {
	*x = PVZReportAggregate{}
	mi := &file_pvz_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZReportAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZReportAggregate) ProtoMessage() {}

func (x *PVZReportAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZReportAggregate.ProtoReflect.Descriptor instead.
func (*PVZReportAggregate) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{4}
}

func (x *PVZReportAggregate) GetPvz() *PVZ {
	if x != nil {
		return x.Pvz
	}
	return nil
}

func (x *PVZReportAggregate) GetReceptions() *ReceptionList {
	if x != nil {
		return x.Receptions
	}
	return nil
}

type PVZ struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreationTimeUtc *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_time_utc,json=creationTimeUtc,proto3" json:"creation_time_utc,omitempty"`
	City            *City                  `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PVZ) Reset() {
	*x = PVZ{}
	mi := &file_pvz_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZ) ProtoMessage() {}

func (x *PVZ) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZ.ProtoReflect.Descriptor instead.
func (*PVZ) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{5}
}

func (x *PVZ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PVZ) GetCreationTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimeUtc
	}
	return nil
}

func (x *PVZ) GetCity() *City {
	if x != nil {
		return x.City
	}
	return nil
}

type City struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_pvz_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{6}
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Product             `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_pvz_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProductList) GetValues() []*Product {
	if x != nil {
		return x.Values
	}
	return nil
}

type Reception struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reception     *ReceptionInfo         `protobuf:"bytes,1,opt,name=reception,proto3" json:"reception,omitempty"`
	Products      *ProductList           `protobuf:"bytes,2,opt,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reception) Reset() {
	*x = Reception{}
	mi := &file_pvz_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reception) ProtoMessage() {}

func (x *Reception) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reception.ProtoReflect.Descriptor instead.
func (*Reception) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{8}
}

func (x *Reception) GetReception() *ReceptionInfo {
	if x != nil {
		return x.Reception
	}
	return nil
}

func (x *Reception) GetProducts() *ProductList {
	if x != nil {
		return x.Products
	}
	return nil
}

type ReceptionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PvzId           string                 `protobuf:"bytes,2,opt,name=pvz_id,json=pvzId,proto3" json:"pvz_id,omitempty"`
	CreationTimeUtc *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=creation_time_utc,json=creationTimeUtc,proto3" json:"creation_time_utc,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceptionInfo) Reset() {
	*x = ReceptionInfo{}
	mi := &file_pvz_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceptionInfo) ProtoMessage() {}

func (x *ReceptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceptionInfo.ProtoReflect.Descriptor instead.
func (*ReceptionInfo) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReceptionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceptionInfo) GetPvzId() string {
	if x != nil {
		return x.PvzId
	}
	return ""
}

func (x *ReceptionInfo) GetCreationTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimeUtc
	}
	return nil
}

func (x *ReceptionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceptionId     string                 `protobuf:"bytes,2,opt,name=reception_id,json=receptionId,proto3" json:"reception_id,omitempty"`
	CreationTimeUtc *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=creation_time_utc,json=creationTimeUtc,proto3" json:"creation_time_utc,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_pvz_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_pvz_service_proto_rawDescGZIP(), []int{10}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetReceptionId() string {
	if x != nil {
		return x.ReceptionId
	}
	return ""
}

func (x *Product) GetCreationTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimeUtc
	}
	return nil
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_pvz_service_proto protoreflect.FileDescriptor

const file_pvz_service_proto_rawDesc = "" +
	"\n" +
	"\x11pvz_service.proto\x12\vpvz_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x10PVZReportRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"h\n" +
	"\x11PVZReportResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12=\n" +
	"\areports\x18\x02 \x01(\v2#.pvz_service.PVZReportAggregateListR\areports\"Q\n" +
	"\x16PVZReportAggregateList\x127\n" +
	"\x06values\x18\x01 \x03(\v2\x1f.pvz_service.PVZReportAggregateR\x06values\"?\n" +
	"\rReceptionList\x12.\n" +
	"\x06values\x18\x01 \x03(\v2\x16.pvz_service.ReceptionR\x06values\"t\n" +
	"\x12PVZReportAggregate\x12\"\n" +
	"\x03pvz\x18\x01 \x01(\v2\x10.pvz_service.PVZR\x03pvz\x12:\n" +
	"\n" +
	"receptions\x18\x02 \x01(\v2\x1a.pvz_service.ReceptionListR\n" +
	"receptions\"\x84\x01\n" +
	"\x03PVZ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\x11creation_time_utc\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreationTimeUtc\x12%\n" +
	"\x04city\x18\x03 \x01(\v2\x11.pvz_service.CityR\x04city\"\x1a\n" +
	"\x04City\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\vProductList\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.pvz_service.ProductR\x06values\"{\n" +
	"\tReception\x128\n" +
	"\treception\x18\x01 \x01(\v2\x1a.pvz_service.ReceptionInfoR\treception\x124\n" +
	"\bproducts\x18\x02 \x01(\v2\x18.pvz_service.ProductListR\bproducts\"\x96\x01\n" +
	"\rReceptionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06pvz_id\x18\x02 \x01(\tR\x05pvzId\x12F\n" +
	"\x11creation_time_utc\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreationTimeUtc\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xa0\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\freception_id\x18\x02 \x01(\tR\vreceptionId\x12F\n" +
	"\x11creation_time_utc\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreationTimeUtc\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory2a\n" +
	"\x10PVZReportService\x12M\n" +
	"\fGetPVZReport\x12\x1d.pvz_service.PVZReportRequest\x1a\x1e.pvz_service.PVZReportResponseB\x10Z\x0e./grpc-profileb\x06proto3"

var (
	file_pvz_service_proto_rawDescOnce sync.Once
	file_pvz_service_proto_rawDescData []byte
)

func file_pvz_service_proto_rawDescGZIP() []byte {
	file_pvz_service_proto_rawDescOnce.Do(func() {
		file_pvz_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pvz_service_proto_rawDesc), len(file_pvz_service_proto_rawDesc)))
	})
	return file_pvz_service_proto_rawDescData
}

var file_pvz_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pvz_service_proto_goTypes = []any{
	(*PVZReportRequest)(nil),       // 0: pvz_service.PVZReportRequest
	(*PVZReportResponse)(nil),      // 1: pvz_service.PVZReportResponse
	(*PVZReportAggregateList)(nil), // 2: pvz_service.PVZReportAggregateList
	(*ReceptionList)(nil),          // 3: pvz_service.ReceptionList
	(*PVZReportAggregate)(nil),     // 4: pvz_service.PVZReportAggregate
	(*PVZ)(nil),                    // 5: pvz_service.PVZ
	(*City)(nil),                   // 6: pvz_service.City
	(*ProductList)(nil),            // 7: pvz_service.ProductList
	(*Reception)(nil),              // 8: pvz_service.Reception
	(*ReceptionInfo)(nil),          // 9: pvz_service.ReceptionInfo
	(*Product)(nil),                // 10: pvz_service.Product
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_pvz_service_proto_depIdxs = []int32{
	11, // 0: pvz_service.PVZReportRequest.start_date:type_name -> google.protobuf.Timestamp
	11, // 1: pvz_service.PVZReportRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 2: pvz_service.PVZReportResponse.reports:type_name -> pvz_service.PVZReportAggregateList
	4,  // 3: pvz_service.PVZReportAggregateList.values:type_name -> pvz_service.PVZReportAggregate
	8,  // 4: pvz_service.ReceptionList.values:type_name -> pvz_service.Reception
	5,  // 5: pvz_service.PVZReportAggregate.pvz:type_name -> pvz_service.PVZ
	3,  // 6: pvz_service.PVZReportAggregate.receptions:type_name -> pvz_service.ReceptionList
	11, // 7: pvz_service.PVZ.creation_time_utc:type_name -> google.protobuf.Timestamp
	6,  // 8: pvz_service.PVZ.city:type_name -> pvz_service.City
	10, // 9: pvz_service.ProductList.values:type_name -> pvz_service.Product
	9,  // 10: pvz_service.Reception.reception:type_name -> pvz_service.ReceptionInfo
	7,  // 11: pvz_service.Reception.products:type_name -> pvz_service.ProductList
	11, // 12: pvz_service.ReceptionInfo.creation_time_utc:type_name -> google.protobuf.Timestamp
	11, // 13: pvz_service.Product.creation_time_utc:type_name -> google.protobuf.Timestamp
	0,  // 14: pvz_service.PVZReportService.GetPVZReport:input_type -> pvz_service.PVZReportRequest
	1,  // 15: pvz_service.PVZReportService.GetPVZReport:output_type -> pvz_service.PVZReportResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pvz_service_proto_init() }
func file_pvz_service_proto_init() {
	if File_pvz_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pvz_service_proto_rawDesc), len(file_pvz_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pvz_service_proto_goTypes,
		DependencyIndexes: file_pvz_service_proto_depIdxs,
		MessageInfos:      file_pvz_service_proto_msgTypes,
	}.Build()
	File_pvz_service_proto = out.File
	file_pvz_service_proto_goTypes = nil
	file_pvz_service_proto_depIdxs = nil
}
