create table cities(
	id bigint primary key,
	name varchar not null
);

insert into cities(id, name) values
		  (1, 'Казань')
		, (2, 'Москва')
		, (3, 'Санкт-Петербург')
		;

create table product_categories(
	id smallint primary key,
	name varchar not null
); 

insert into product_categories(id, name) values
		  (1, 'Электроника')
		, (2, 'Одежда')
		, (3, 'Обувь')
		;

create table products(
	id uuid primary key,
	reception_id uuid not null,
	creation_time_utc timestamp without time zone not null,
	category smallint not null
);

create table receptions (
	id uuid primary key,
	pvz_id uuid not null,
    creation_time_utc timestamp without time zone not null,
    status smallint not null
);

create view receptions_with_products_view as
select 
    	r.id
	  , r.pvz_id	
      , to_char(r.creation_time_utc at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') as creation_time_utc
      , r.status
      , (select array_to_json(array_agg(row_to_json(p)))
           from (select 
		   				  p.id
						, p.reception_id
                        , to_char(p.creation_time_utc at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') as creation_time_utc
						, p.category
                   from products p
                  where p.reception_id = r.id
           ) p
        ) as products
  from receptions r;

create table pvzs(
	id uuid primary key,
	creation_time_utc timestamp without time zone not null,
	city_id  bigint not null,
	pvz_record_number bigint generated by default as identity not null
);

create unique index pvzs_pagination_index_uq on pvzs(pvz_record_number);

create table user_roles(
	id smallint primary key generated by default as identity,
	name varchar not null
);

insert into user_roles(id, name) values
	  (1, 'client')
	, (2, 'moderator')
	;

create table users(
	id uuid primary key,
	user_role_id smallint not null,
	email varchar not null,
	password varchar not null,

	constraint users_unique_email unique(email)
);

insert into users(id, user_role_id, email, password) values 
	  /* dummy user */						-- client role	
	  ('0196521c-873e-77fd-b244-bdd0c13c72ab', 1, 'example@example.com', '')
	  /* dummy moderator */					-- moderator role
	, ('0196521c-b2a9-7a04-88be-16ec981d104b', 2,'example2@example.com', '');
